### ISSUE TITLE
Can't get anything working.

### ISSUE THREAD

**Issue by aliteralmind** [jhusain/learnrx#47]
I've just executed the workaround for [this bug](https://github.com/jhusain/learnrx/issues/9#issuecomment-68357146), and this is printed to the console:

    HTMLElement.prototype.innerText = function() { return this.textContent; }
    function()

I now see the first three tests, but when I click "run", nothing is printed to the console. On the third test, however, when you click "Show answer", the following error is printed to the console: 

    TypeError: string.split is not a function
    http://reactive-extensions.github.io/learnrx/assets/codemirror/codemirror.js
    Line 3124

Otherwise, no output. I'm on Firefox 35.0.1, Windows 8.1, 64bit. I have the NoScript 2.6.9.10 Firefox plugin installed, but it's currently set to "Allow scripts globally" (which is temporary only for this tutorial). I also have Ghostery and AdBlock Plus, if that makes a difference.

**Comment by morenoh149** [comment]
I've merged in many changes. Please reopen the issue if you are still experiencing troubles.
