### ISSUE TITLE
Confusion with reactive-extensions.github.io/learnrx/

### ISSUE THREAD

**Issue by jefffriesen** [jhusain/learnrx#60]
There's an older, forked repo here: http://reactive-extensions.github.io/learnrx/

That repo looks like it diverges around exercise 10 with mergeAll.

Of course anyone can fork a repo, but that one looks like an official repo from MicroSoft but hasn't been updated for a ~1.5 years, whereas this repo looks active. Adding to the confusion (at least mine), this repo points to their exercises in the readme, as opposed to http://jhusain.github.io/learnrx/

A couple suggestions:
1. Maybe MS could either take theirs down if no longer relevant or point to yours
2. This readme could point to http://jhusain.github.io/learnrx/

**Comment by morenoh149** [comment]
Fixed
