### ISSUE TITLE
Cannot read property 'answers' of null

### ISSUE THREAD

**Issue by Vadorequest** [jhusain/learnrx#61]
Here is what I get by loading the page: https://jhusain.github.io/learnrx/
I haven't done anything, just loaded the page and looking at the console.

```
Uncaught TypeError: Cannot read property 'answers' of null
(anonymous function) @ main.js:29
x.extend.each @ jquery-1.10.2.min.js:4
x.fn.x.each @ jquery-1.10.2.min.js:4
window.onload @ main.js:24
```

**Comment by morenoh149** [comment]
I think these have been resolved. Reopen if it's not the case.
