### ISSUE TITLE
concatAll() is not a function, Exercise: 12

### ISSUE THREAD

**Issue by saadehmad** [jhusain/learnrx#68]
I have solved Exercise 12, but I can't go any further because, when I click on run this error pop up ( TypeError: movieList.videos.map(...).concatAll is not a function ).

**Comment by haveagoodone** [comment]
Try to rerun the concatAll()-function in Exercise 10.

**Comment by saadehmad** [comment]
I don't know what was the problem going on, but when I refresh the page then other exercise unlocked so aging I try to run the solution but the problem exist. In exercise 10 nothings pop up when I click run but it runs fine.

**Comment by nxiety** [comment]
Keeps happening to me as well. I have to keep showing answer/running the previous exercises to get them to all work again.

**Comment by morenoh149** [comment]
Fixed
