### ISSUE TITLE
Unclear direction

### ISSUE THREAD

**Issue by talymo** [jhusain/learnrx#81]
A lot of the problems have solutions that require methods that are not explained or introduced in the text preceding the problem. Specifically on Exercise 10, I would have never arrived at the answer because .apply() was never explained to me. Even to this moment I have no idea what the .apply() method does in this specific piece of code, therefore resulting in me having to leave your tutorial and find the answers elsewhere.

This leads me to wonder, why use this tutorial at all if all the information I need is not supplied to me?

Coming to this as someone who is not familiar with the core methods in JavaScript, it has been a very frustrating experience and the only reason I will continue on with this is because it is a requirement from FreeCodeCamp to proceed through their tutorials. If a user who has never used JavaScript before came to this tutorial and was expecting to learn anything from it, they would get a bit of info, but nothing like the abundance of other tutorials out there that actually take the time to walk you through the code and explain everything.

My suggestion is to spend some time, perhaps do some user testing, find out where this tutorial is lacking and update it to be a solid tutorial. If you do not have the resources or interest in doing this, then perhaps removing it from the general public would be the best solution.

**Comment by peteruithoven** [comment]
I have found this tutorial very useful to get to know reactive programming specifically. I agree that understanding `apply` requires some more javascript knowledge, and but that doesn't mean it doesn't have an audience. 

@talymo, since you noticed this explanation gap, you might be in better position than most to suggest improvements, even if it's just a few links here and there.

**Comment by morenoh149** [comment]
@talymo indeed. PRs from persons confused with the tutorial are very welcome. I'll try to merge in anything that makes sense.
