### ISSUE TITLE
concatAll() and concatMap() don't work when you resume a session.

### ISSUE THREAD

**Issue by Em-Ant** [jhusain/learnrx#83]
When you come back the the page to continue the tutorial, you need to re-run the exercises **10** and **13**, or the other exercises needing *concatAll()* and *concatMap()* won't run. These function should be automatically added to  *Array.prototype* by the browser, when it finds related data on local storage.

**Comment by morenoh149** [comment]
fixed by https://github.com/jhusain/learnrx/commit/7eab441c5c95b4cea65652e50085d23700d392bd
