### ISSUE TITLE
TypeError: verifier is not a function

### ISSUE THREAD

**Issue by gliptak** [jhusain/learnrx#9]
In Firefox 19.0.2, I see this following error when trying to run the first exercise:
```TypeError: verifier is not a function```
Please comment. Thanks

**Comment by aliteralmind** [comment]
Happens for me, too, in Firefox 35.0.1, Windows 8.1, 64bit. The [suggested solution](https://github.com/jhusain/learnrx/issues/9#issuecomment-68357146) also works.

**Comment by morenoh149** [comment]
I can't find `innerText` used in index.html on the gh-pages branch anymore. Closing.
